"""Change date

Revision ID: ea6028930f24
Revises: bac2cad3bc5a
Create Date: 2025-08-20 11:17:09.762636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6028930f24'
down_revision: Union[str, Sequence[str], None] = 'bac2cad3bc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apod', 'url',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('apod', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apod', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('apod', 'url',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
