# Dockerfile
FROM python:3.10-slim

ENV PATH="/root/.local/bin:${PATH}"

# 作業ディレクトリを設定
WORKDIR /app

# Poetry自体のインストール
RUN pip install poetry

# Poetryが仮想環境をプロジェクト内に作らないように設定
# (Dockerではコンテナ自体が環境分離の役割を果たすため)
RUN poetry config virtualenvs.create false

# 依存関係ファイルを先にコピー
COPY ./pyproject.toml ./poetry.lock* /app/

# --no-devオプションで本番用のライブラリのみインストール
# --no-rootはプロジェクト自体はインストールしないオプション
RUN poetry install --no-root --without dev

# アプリケーションコードをコピー
COPY . .