# Dockerfile
# Pythonの公式イメージを使用
FROM python:3.10-slim

ENV PATH="/root/.local/bin:${PATH}"

# 作業ディレクトリを設定
WORKDIR /app

# requirements.txtをコンテナにコピー
COPY requirements.txt .

# 必要なPythonライブラリをインストール
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションのコードをコンテナにコピー
COPY . .